export const ugandaUniversitiesData = [
  {
    name: "Makerere University",
    location: "Kampala",
    type: "public" as const,
    status: "chartered" as const,
    description: "Established in 1922, Uganda's oldest and largest university offering comprehensive programs across all disciplines. Known for excellence in research and academic programs.",
    tuitionMin: "1500000",
    tuitionMax: "4000000",
    websiteUrl: "https://www.mak.ac.ug",
    applicationPortalUrl: "https://apply.mak.ac.ug",
    logoUrl: "/attached_assets/makerere-university-uganda_1764928321778.png",
    established: 1922,
    ranking: 1,
    specialties: ["Medicine", "Engineering", "Business", "Law", "Agriculture", "Humanities"]
  },
  {
    name: "Mbarara University of Science and Technology",
    location: "Mbarara",
    type: "public" as const,
    status: "chartered" as const,
    description: "Leading institution for science, technology, and health sciences with strong research programs and modern facilities.",
    tuitionMin: "2000000",
    tuitionMax: "5000000",
    websiteUrl: "https://www.must.ac.ug",
    applicationPortalUrl: "https://applications.must.ac.ug",
    logoUrl: "/attached_assets/mbarara-university-of-science-technology-png_1764926452824.png",
    established: 1989,
    ranking: 2,
    specialties: ["Medicine", "Science & Technology", "Health Sciences", "Computing", "Development Studies"]
  },
  {
    name: "Kyambogo University",
    location: "Kampala",
    type: "public" as const,
    status: "chartered" as const,
    description: "Education and technology focused university providing quality training for teachers and technical professionals.",
    tuitionMin: "1400000",
    tuitionMax: "3800000",
    websiteUrl: "https://www.kyu.ac.ug",
    applicationPortalUrl: "https://apply.kyu.ac.ug",
    logoUrl: "/attached_assets/kyambogo-university-logo-png_1764926452826.png",
    established: 2003,
    ranking: 3,
    specialties: ["Education", "Engineering", "Special Needs Education", "Vocational Studies"]
  },
  {
    name: "Uganda Christian University",
    location: "Mukono",
    type: "private" as const,
    status: "chartered" as const,
    description: "First private chartered university (2004) offering quality education with Christian values and holistic development.",
    tuitionMin: "3000000",
    tuitionMax: "6000000",
    websiteUrl: "https://www.ucu.ac.ug",
    applicationPortalUrl: "https://application.ucu.ac.ug",
    logoUrl: "/attached_assets/uganda-christian-university-logo-png_1764926452824.png",
    established: 1997,
    ranking: 4,
    specialties: ["Theology", "Business", "Law", "Journalism", "Education", "Social Sciences"]
  },
  {
    name: "Gulu University",
    location: "Gulu",
    type: "public" as const,
    status: "chartered" as const,
    description: "Northern Uganda's flagship university focusing on regional development, agriculture, and community engagement.",
    tuitionMin: "1800000",
    tuitionMax: "4500000",
    websiteUrl: "https://www.gu.ac.ug",
    applicationPortalUrl: "https://admissions.gu.ac.ug",
    logoUrl: "/attached_assets/Gulu-university_logo_1764926452822.png",
    established: 2002,
    ranking: 5,
    specialties: ["Agriculture", "Education", "Medicine", "Business", "Engineering"]
  },
  {
    name: "Busitema University",
    location: "Busitema",
    type: "public" as const,
    status: "chartered" as const,
    description: "Engineering and agriculture focused institution with emphasis on practical skills and innovation.",
    tuitionMin: "1600000",
    tuitionMax: "4200000",
    websiteUrl: "https://www.busitema.ac.ug",
    applicationPortalUrl: "https://apply.busitema.ac.ug",
    logoUrl: "/attached_assets/busitema-university-logo-png_1764926452822.png",
    established: 2007,
    ranking: 6,
    specialties: ["Engineering", "Agriculture", "Applied Sciences", "Health Sciences"]
  },
  {
    name: "Uganda Martyrs University",
    location: "Nkozi",
    type: "private" as const,
    status: "chartered" as const,
    description: "Catholic university known for excellence in liberal arts, business, and social sciences education.",
    tuitionMin: "2800000",
    tuitionMax: "5800000",
    websiteUrl: "https://www.umu.ac.ug",
    applicationPortalUrl: "https://apply.umu.ac.ug",
    logoUrl: "/attached_assets/uganda-martyrs-university-logo-png_1764926452819.png",
    established: 1993,
    ranking: 7,
    specialties: ["Business", "Social Sciences", "Education", "Ethics & Development Studies"]
  },
  {
    name: "Kampala International University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Comprehensive private university with diverse programs and international partnerships for global education opportunities.",
    tuitionMin: "2500000",
    tuitionMax: "7000000",
    websiteUrl: "https://www.kiu.ac.ug",
    applicationPortalUrl: "https://applications.kiu.ac.ug",
    logoUrl: "/attached_assets/kampala-international-university-logo-png_1764926452819.png",
    established: 2001,
    ranking: 8,
    specialties: ["Medicine", "Engineering", "Business", "Law", "Pharmacy", "Nursing"]
  },
  {
    name: "Islamic University in Uganda",
    location: "Mbale",
    type: "private" as const,
    status: "chartered" as const,
    description: "Islamic institution offering diverse programs with emphasis on Islamic values, ethics, and comprehensive education.",
    tuitionMin: "2000000",
    tuitionMax: "5500000",
    websiteUrl: "https://www.iuiu.ac.ug",
    applicationPortalUrl: "https://apply.iuiu.ac.ug",
    logoUrl: "/attached_assets/iuiu-logo-png_1764926452823.png",
    established: 1988,
    ranking: 9,
    specialties: ["Islamic Studies", "Education", "Management", "Science & Technology"]
  },
  {
    name: "Muni University",
    location: "Arua",
    type: "public" as const,
    status: "chartered" as const,
    description: "Serving the West Nile region with focus on regional development and community engagement.",
    tuitionMin: "1700000",
    tuitionMax: "4300000",
    websiteUrl: "https://www.muni.ac.ug",
    applicationPortalUrl: "https://admissions.muni.ac.ug",
    logoUrl: "/attached_assets/muni-university-logo-png_1764926452817.png",
    established: 2013,
    ranking: 10,
    specialties: ["Medicine", "Applied Sciences", "Education", "Agriculture"]
  },
  {
    name: "Ndejje University",
    location: "Luwero",
    type: "private" as const,
    status: "chartered" as const,
    description: "One of Uganda's oldest private universities established in 1992, offering diverse academic programs.",
    tuitionMin: "2200000",
    tuitionMax: "5200000",
    websiteUrl: "https://www.ndejjeuniversity.ac.ug",
    applicationPortalUrl: "https://apply.ndejjeuniversity.ac.ug",
    logoUrl: "/attached_assets/ndejje-university-logo-png_1764926452818.png",
    established: 1992,
    ranking: 11,
    specialties: ["Business", "Education", "Social Sciences", "Information Technology"]
  },
  {
    name: "Nkumba University",
    location: "Entebbe",
    type: "private" as const,
    status: "chartered" as const,
    description: "Business-focused private university located near Lake Victoria with modern facilities.",
    tuitionMin: "2400000",
    tuitionMax: "5600000",
    websiteUrl: "https://www.nkumbauniversity.ac.ug",
    applicationPortalUrl: "https://application.nkumbauniversity.ac.ug",
    logoUrl: "/attached_assets/nkumba-university-logo-png_1764926452818.png",
    established: 1994,
    ranking: 12,
    specialties: ["Business", "Computing", "Social Sciences", "Mass Communication"]
  },
  {
    name: "Kabale University",
    location: "Kabale",
    type: "public" as const,
    status: "chartered" as const,
    description: "Southwestern regional university with emphasis on agriculture and development studies.",
    tuitionMin: "1500000",
    tuitionMax: "4000000",
    websiteUrl: "https://www.kab.ac.ug",
    applicationPortalUrl: "https://apply.kab.ac.ug",
    logoUrl: "/attached_assets/kabale-university-logo-png_1764926452817.png",
    established: 2015,
    ranking: 13,
    specialties: ["Agriculture", "Education", "Development Studies", "Business"]
  },
  {
    name: "Mountains of the Moon University",
    location: "Fort Portal",
    type: "public" as const,
    status: "chartered" as const,
    description: "Regional university serving western Uganda with focus on community development.",
    tuitionMin: "2100000",
    tuitionMax: "4800000",
    websiteUrl: "https://www.mmu.ac.ug",
    applicationPortalUrl: "https://apply.mmu.ac.ug",
    logoUrl: "/attached_assets/mountains-of-the-moon-university-logo-png_1764926452816.png",
    established: 2005,
    ranking: 14,
    specialties: ["Health Sciences", "Business", "Education", "Development Studies"]
  },
  {
    name: "Cavendish University Uganda",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "International university offering globally recognized programs with modern facilities.",
    tuitionMin: "3200000",
    tuitionMax: "7200000",
    websiteUrl: "https://www.cavendish.ac.ug",
    applicationPortalUrl: "https://apply.cavendish.ac.ug",
    logoUrl: "/attached_assets/cavendish-university-uganda-logo-png_1764926452815.png",
    established: 2008,
    ranking: 15,
    specialties: ["Business", "Law", "Psychology", "Information Technology"]
  },
  {
    name: "Soroti University",
    location: "Soroti",
    type: "public" as const,
    status: "chartered" as const,
    description: "Eastern Uganda university focusing on agriculture, education, and regional development.",
    tuitionMin: "1600000",
    tuitionMax: "4100000",
    websiteUrl: "https://www.soru.ac.ug",
    applicationPortalUrl: "https://apply.soru.ac.ug",
    logoUrl: "/attached_assets/soroti-university-logo-png_1764928321777.png",
    established: 2015,
    ranking: 16,
    specialties: ["Agriculture", "Education", "Applied Sciences", "Business"]
  },
  {
    name: "Lira University",
    location: "Lira",
    type: "public" as const,
    status: "chartered" as const,
    description: "Northern Uganda university focusing on agriculture, education, and regional development.",
    tuitionMin: "1600000",
    tuitionMax: "4100000",
    websiteUrl: "https://www.lirauni.ac.ug",
    applicationPortalUrl: "https://apply.lirauni.ac.ug",
    logoUrl: "/attached_assets/Lira_university_logo_1764926452814.png",
    established: 2015,
    ranking: 17,
    specialties: ["Agriculture", "Education", "Applied Sciences"]
  },
  {
    name: "Bishop Stuart University",
    location: "Mbarara",
    type: "private" as const,
    status: "chartered" as const,
    description: "Anglican university in southwestern Uganda focusing on holistic education.",
    tuitionMin: "2200000",
    tuitionMax: "5000000",
    websiteUrl: "https://www.bsu.ac.ug",
    applicationPortalUrl: "https://apply.bsu.ac.ug",
    logoUrl: "/attached_assets/bishop-stuart-university-logo-png_1764928321765.png",
    established: 2003,
    ranking: 18,
    specialties: ["Theology", "Education", "Development Studies", "Business"]
  },
  {
    name: "Clarke International University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Health sciences focused university providing quality medical and nursing education.",
    tuitionMin: "3500000",
    tuitionMax: "8000000",
    websiteUrl: "https://www.ciu.ac.ug",
    applicationPortalUrl: "https://apply.ciu.ac.ug",
    logoUrl: "/attached_assets/clarke-international-university-logo-png_1764928321777.png",
    established: 2008,
    ranking: 19,
    specialties: ["Medicine", "Nursing", "Public Health", "Pharmacy"]
  },
  {
    name: "Bugema University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Seventh-day Adventist university offering holistic education with emphasis on Christian values.",
    tuitionMin: "2300000",
    tuitionMax: "5400000",
    websiteUrl: "https://www.bugema.ac.ug",
    applicationPortalUrl: "https://apply.bugema.ac.ug",
    logoUrl: "/attached_assets/bugema-university-logo-png_1764928321776.png",
    established: 1994,
    ranking: 20,
    specialties: ["Theology", "Business", "Education", "Health Sciences"]
  },
  {
    name: "Victoria University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Recently chartered university offering contemporary programs in business and technology.",
    tuitionMin: "2800000",
    tuitionMax: "6500000",
    websiteUrl: "https://www.vu.ac.ug",
    applicationPortalUrl: "https://apply.vu.ac.ug",
    logoUrl: "/attached_assets/victoria-university-logo-png_1764928321775.png",
    established: 2011,
    ranking: 21,
    specialties: ["Business", "Information Technology", "Social Sciences"]
  },
  {
    name: "Kampala University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Urban private university offering business and social sciences programs in the heart of Kampala.",
    tuitionMin: "2300000",
    tuitionMax: "5500000",
    websiteUrl: "https://www.ku.ac.ug",
    applicationPortalUrl: "https://apply.ku.ac.ug",
    logoUrl: "/attached_assets/kampala-university-the-original-ku-logo-png_1764928321775.png",
    established: 2005,
    ranking: 22,
    specialties: ["Business", "Social Sciences", "Education", "Information Technology"]
  },
  {
    name: "Busoga University",
    location: "Iganga",
    type: "private" as const,
    status: "chartered" as const,
    description: "Serving the Busoga region with diverse academic programs and community development focus.",
    tuitionMin: "2100000",
    tuitionMax: "5000000",
    websiteUrl: "https://www.busogauniversity.ac.ug",
    applicationPortalUrl: "https://apply.busogauniversity.ac.ug",
    logoUrl: "/attached_assets/Busoga_university_1764928321774.jpg",
    established: 1999,
    ranking: 23,
    specialties: ["Business", "Education", "Agriculture", "Health Sciences"]
  },
  {
    name: "International University of East Africa",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Technology and business focused university with modern programs and facilities.",
    tuitionMin: "2600000",
    tuitionMax: "6200000",
    websiteUrl: "https://www.iuea.ac.ug",
    applicationPortalUrl: "https://apply.iuea.ac.ug",
    logoUrl: "/attached_assets/international-university-of-east-africa-logo-png_1764928321773.png",
    established: 2010,
    ranking: 24,
    specialties: ["Information Technology", "Business", "Engineering", "Health Sciences"]
  },
  {
    name: "St. Lawrence University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Private university offering business and social sciences programs with strong industry connections.",
    tuitionMin: "2500000",
    tuitionMax: "5800000",
    websiteUrl: "https://www.slau.ac.ug",
    applicationPortalUrl: "https://apply.slau.ac.ug",
    logoUrl: "/attached_assets/St_lawrence_university_1764980297180.jpeg",
    established: 2007,
    ranking: 25,
    specialties: ["Business", "Education", "Social Sciences", "Information Technology"]
  },
  {
    name: "Kisubi University",
    location: "Entebbe",
    type: "private" as const,
    status: "chartered" as const,
    description: "Catholic university offering quality education with strong community engagement.",
    tuitionMin: "2500000",
    tuitionMax: "5700000",
    websiteUrl: "https://www.kisubi.ac.ug",
    applicationPortalUrl: "https://apply.kisubi.ac.ug",
    logoUrl: "/attached_assets/university-of-kisubi-logo-png_1764928321768.png",
    established: 2008,
    ranking: 26,
    specialties: ["Business", "Education", "Social Sciences", "Development Studies"]
  },
  {
    name: "Team University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Modern private university with innovative programs and entrepreneurship focus.",
    tuitionMin: "2400000",
    tuitionMax: "5600000",
    websiteUrl: "https://www.teamuniversity.ac.ug",
    applicationPortalUrl: "https://apply.teamuniversity.ac.ug",
    logoUrl: "/attached_assets/team-university-kampala-logo-png_1764928321769.png",
    established: 2009,
    ranking: 27,
    specialties: ["Business", "Information Technology", "Media Studies", "Social Sciences"]
  },
  {
    name: "Uganda Pentecostal University",
    location: "Fort Portal",
    type: "private" as const,
    status: "chartered" as const,
    description: "Pentecostal university offering education rooted in Christian values and community service.",
    tuitionMin: "2200000",
    tuitionMax: "5100000",
    websiteUrl: "https://www.upu.ac.ug",
    applicationPortalUrl: "https://apply.upu.ac.ug",
    logoUrl: "/attached_assets/uganda-pentecostal-university-logo-png_1764928321772.png",
    established: 2005,
    ranking: 28,
    specialties: ["Theology", "Education", "Business", "Social Work"]
  },
  {
    name: "Kayiwa International University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Private university offering diverse programs with international standards.",
    tuitionMin: "2600000",
    tuitionMax: "6000000",
    websiteUrl: "https://www.kayiwa.ac.ug",
    applicationPortalUrl: "https://apply.kayiwa.ac.ug",
    logoUrl: "/attached_assets/Kintu_1764928321771.jpg",
    established: 2010,
    ranking: 29,
    specialties: ["Business", "Education", "Health Sciences", "Information Technology"]
  },
  {
    name: "African Bible University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Christian university focused on biblical studies and leadership development.",
    tuitionMin: "2000000",
    tuitionMax: "4500000",
    websiteUrl: "https://www.abu.ac.ug",
    applicationPortalUrl: "https://apply.abu.ac.ug",
    logoUrl: "/attached_assets/african-bible-university-uganda-logo-png_1764928321773.png",
    established: 2005,
    ranking: 30,
    specialties: ["Theology", "Biblical Studies", "Leadership", "Education"]
  }
];

export const ugandaScholarshipsData = [
  {
    title: "Chevening Scholarships",
    description: "UK government's global scholarship for fully-funded one-year master's degrees for future leaders.",
    provider: "UK Foreign, Commonwealth & Development Office",
    amount: "30000000",
    currency: "UGX",
    eligibility: "Bachelor's degree, two years work experience, leadership potential.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2024-11-05"),
    applicationUrl: "https://www.chevening.org/",
    isActive: true
  },
  {
    title: "Mastercard Foundation Scholars Program",
    description: "Comprehensive scholarship covering tuition, accommodation, and mentorship for talented African students.",
    provider: "Mastercard Foundation",
    amount: "20000000",
    currency: "UGX",
    eligibility: "Academically talented with leadership potential, financial need, commitment to giving back to Africa.",
    level: "both" as const,
    type: "international" as const,
    deadline: new Date("2025-02-15"),
    applicationUrl: "https://mastercardfdn.org/",
    isActive: true
  },
  {
    title: "Uganda Government Scholarship",
    description: "Full scholarship for outstanding Ugandan students to study at public universities.",
    provider: "Government of Uganda",
    amount: "5000000",
    currency: "UGX",
    eligibility: "Ugandan citizen, excellent A-level results, financial need.",
    level: "undergraduate" as const,
    type: "government" as const,
    deadline: new Date("2025-03-31"),
    applicationUrl: "https://www.education.go.ug/",
    isActive: true
  },
  {
    title: "Makerere University Staff Development Scholarship",
    description: "Scholarship for Makerere University staff members pursuing postgraduate studies.",
    provider: "Makerere University",
    amount: "15000000",
    currency: "UGX",
    eligibility: "Current Makerere staff, minimum 2 years service, excellent academic record.",
    level: "postgraduate" as const,
    type: "government" as const,
    deadline: new Date("2025-04-15"),
    applicationUrl: "https://www.mak.ac.ug/",
    isActive: true
  },
  {
    title: "African Leadership Academy Scholarship",
    description: "Two-year pre-university program developing Africa's next generation of leaders.",
    provider: "African Leadership Academy",
    amount: "25000000",
    currency: "UGX",
    eligibility: "African students aged 16-19, leadership potential, academic excellence.",
    level: "undergraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-01-15"),
    applicationUrl: "https://www.africanleadershipacademy.org/",
    isActive: true
  },
  {
    title: "DAAD Scholarships",
    description: "German Academic Exchange Service scholarships for study and research in Germany.",
    provider: "German Academic Exchange Service (DAAD)",
    amount: "35000000",
    currency: "UGX",
    eligibility: "Bachelor's degree, relevant work experience, excellent academic record.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-07-31"),
    applicationUrl: "https://www.daad.de/",
    isActive: true
  },
  {
    title: "Fulbright Foreign Student Program",
    description: "U.S. government flagship exchange program for graduate study in the United States.",
    provider: "U.S. Department of State",
    amount: "40000000",
    currency: "UGX",
    eligibility: "Bachelor's degree, strong academic record, leadership qualities.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-04-30"),
    applicationUrl: "https://ug.usembassy.gov/education-culture/fulbright/",
    isActive: true
  },
  {
    title: "Commonwealth Shared Scholarships",
    description: "For students from developing Commonwealth countries to study in the UK.",
    provider: "Commonwealth Scholarship Commission",
    amount: "28000000",
    currency: "UGX",
    eligibility: "Commonwealth citizen, bachelor's degree, unable to afford UK study.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-02-28"),
    applicationUrl: "https://cscuk.fcdo.gov.uk/",
    isActive: true
  },
  {
    title: "UCU Merit Scholarship",
    description: "Merit-based scholarship for outstanding students at Uganda Christian University.",
    provider: "Uganda Christian University",
    amount: "4000000",
    currency: "UGX",
    eligibility: "Minimum aggregate of 14 points at A-level, financial need.",
    level: "undergraduate" as const,
    type: "private" as const,
    deadline: new Date("2025-05-30"),
    applicationUrl: "https://www.ucu.ac.ug/",
    isActive: true
  },
  {
    title: "MTN Uganda Foundation Scholarship",
    description: "Supporting bright students from disadvantaged backgrounds in STEM fields.",
    provider: "MTN Uganda Foundation",
    amount: "8000000",
    currency: "UGX",
    eligibility: "Ugandan citizen, excellent academic performance, STEM interest, financial need.",
    level: "undergraduate" as const,
    type: "private" as const,
    deadline: new Date("2025-06-30"),
    applicationUrl: "https://www.mtn.co.ug/foundation/",
    isActive: true
  },
  {
    title: "Stanbic Bank Uganda Scholarship",
    description: "Supporting education for exceptional students pursuing business and finance studies.",
    provider: "Stanbic Bank Uganda",
    amount: "6000000",
    currency: "UGX",
    eligibility: "Ugandan citizen, pursuing business/finance, excellent academics, financial need.",
    level: "undergraduate" as const,
    type: "private" as const,
    deadline: new Date("2025-03-15"),
    applicationUrl: "https://www.stanbicbank.co.ug/",
    isActive: true
  },
  {
    title: "KCCA Education Scholarship",
    description: "Kampala Capital City Authority scholarship for students from Kampala.",
    provider: "KCCA",
    amount: "3500000",
    currency: "UGX",
    eligibility: "Resident of Kampala, excellent academic performance, demonstrated need.",
    level: "undergraduate" as const,
    type: "government" as const,
    deadline: new Date("2025-04-30"),
    applicationUrl: "https://www.kcca.go.ug/",
    isActive: true
  },
  {
    title: "Australia Awards Scholarships",
    description: "Full scholarships for study at Australian universities in development priority areas.",
    provider: "Australian Government",
    amount: "45000000",
    currency: "UGX",
    eligibility: "Ugandan citizen, bachelor's degree, 2+ years work experience, returning to Uganda.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-04-30"),
    applicationUrl: "https://www.australiaawardsafrica.org/",
    isActive: true
  },
  {
    title: "Japanese Government MEXT Scholarship",
    description: "Full scholarship for undergraduate and graduate study in Japan.",
    provider: "Government of Japan",
    amount: "38000000",
    currency: "UGX",
    eligibility: "Under 35 years, excellent academic record, willingness to learn Japanese.",
    level: "both" as const,
    type: "international" as const,
    deadline: new Date("2025-04-15"),
    applicationUrl: "https://www.ug.emb-japan.go.jp/",
    isActive: true
  },
  {
    title: "KIU Medical Scholarship",
    description: "Merit scholarship for medical students at Kampala International University.",
    provider: "Kampala International University",
    amount: "10000000",
    currency: "UGX",
    eligibility: "Excellent A-level results in sciences, pursuing medicine, financial need.",
    level: "undergraduate" as const,
    type: "private" as const,
    deadline: new Date("2025-07-31"),
    applicationUrl: "https://www.kiu.ac.ug/",
    isActive: true
  },
  {
    title: "NSSF Higher Education Loan Scheme",
    description: "Education loan scheme for children of NSSF members for university study.",
    provider: "National Social Security Fund",
    amount: "12000000",
    currency: "UGX",
    eligibility: "Parent/guardian is NSSF member, admitted to recognized university.",
    level: "undergraduate" as const,
    type: "government" as const,
    deadline: new Date("2025-08-31"),
    applicationUrl: "https://www.nssfug.org/",
    isActive: true
  },
  {
    title: "Chinese Government Scholarship",
    description: "Full scholarship for undergraduate, master's, and doctoral study in China.",
    provider: "Chinese Government",
    amount: "32000000",
    currency: "UGX",
    eligibility: "Under 25 (undergraduate) or 35 (masters), good health, no Chinese citizenship.",
    level: "both" as const,
    type: "international" as const,
    deadline: new Date("2025-03-31"),
    applicationUrl: "https://www.campuschina.org/",
    isActive: true
  },
  {
    title: "African Women in Science Scholarship",
    description: "Supporting female students pursuing STEM degrees at Ugandan universities.",
    provider: "African Institute for Mathematical Sciences",
    amount: "7000000",
    currency: "UGX",
    eligibility: "Female Ugandan student, pursuing STEM, excellent academic record.",
    level: "undergraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-05-15"),
    applicationUrl: "https://www.aims.ac.za/",
    isActive: true
  },
  {
    title: "Rotary Foundation Global Grant",
    description: "Funding for graduate-level study in one of Rotary's areas of focus.",
    provider: "Rotary Foundation",
    amount: "30000000",
    currency: "UGX",
    eligibility: "Graduate study in Rotary focus areas, sponsored by local Rotary club.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-06-15"),
    applicationUrl: "https://www.rotary.org/",
    isActive: true
  },
  {
    title: "Uganda National Teachers Union Scholarship",
    description: "Supporting teachers pursuing further education in education-related fields.",
    provider: "Uganda National Teachers' Union",
    amount: "4500000",
    currency: "UGX",
    eligibility: "Registered teacher, UNATU member, pursuing education degree.",
    level: "both" as const,
    type: "private" as const,
    deadline: new Date("2025-05-31"),
    applicationUrl: "https://www.unatu.org/",
    isActive: true
  }
];

export const servicesData = [
  {
    name: "University Application Assistance",
    description: "Complete support for university applications including document preparation, personal statement writing, and application submission guidance.",
    tier: "premium" as const,
    isActive: true
  },
  {
    name: "Professional Resume Writing",
    description: "Expert CV/resume writing service tailored for academic and professional applications.",
    tier: "standard" as const,
    isActive: true
  },
  {
    name: "Scholarship Essay Review",
    description: "Professional review and editing of scholarship application essays to improve your chances of success.",
    tier: "standard" as const,
    isActive: true
  },
  {
    name: "Career Counseling Session",
    description: "One-on-one career guidance session to help you choose the right course and university.",
    tier: "premium" as const,
    isActive: true
  },
  {
    name: "Document Verification Service",
    description: "Assistance with verification and authentication of academic documents.",
    tier: "standard" as const,
    isActive: true
  },
  {
    name: "Interview Preparation",
    description: "Mock interview sessions and coaching to prepare for university or scholarship interviews.",
    tier: "premium" as const,
    isActive: true
  },
  {
    name: "Appeal Letter Writing",
    description: "Expert assistance in crafting compelling appeal letters for university admissions or scholarship reconsideration.",
    tier: "premium" as const,
    isActive: true
  }
];
