export const ugandaUniversitiesData = [
  {
    name: "Makerere University",
    location: "Kampala",
    type: "public" as const,
    status: "chartered" as const,
    description: "Established in 1922, Uganda's oldest and largest university offering comprehensive programs across all disciplines. Known for excellence in research and academic programs.",
    tuitionMin: "1500000",
    tuitionMax: "4000000",
    websiteUrl: "https://www.mak.ac.ug",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Makerere_University_coat_of_arms.svg/200px-Makerere_University_coat_of_arms.svg.png",
    established: 1922,
    specialties: ["Medicine", "Engineering", "Business", "Law", "Agriculture", "Humanities"]
  },
  {
    name: "Kyambogo University",
    location: "Kampala",
    type: "public" as const,
    status: "chartered" as const,
    description: "Education and technology focused university providing quality training for teachers and technical professionals.",
    tuitionMin: "1400000",
    tuitionMax: "3800000",
    websiteUrl: "https://www.kyu.ac.ug",
    logoUrl: "https://www.kyu.ac.ug/images/kyu-logo.png",
    established: 2003,
    specialties: ["Education", "Engineering", "Special Needs Education", "Vocational Studies"]
  },
  {
    name: "Gulu University",
    location: "Gulu",
    type: "public" as const,
    status: "chartered" as const,
    description: "Northern Uganda's flagship university focusing on regional development, agriculture, and community engagement.",
    tuitionMin: "1800000",
    tuitionMax: "4500000",
    websiteUrl: "https://www.gu.ac.ug",
    logoUrl: "https://gu.ac.ug/wp-content/uploads/2020/03/gulu-university-logo.png",
    established: 2002,
    specialties: ["Agriculture", "Education", "Medicine", "Business", "Engineering"]
  },
  {
    name: "Busitema University",
    location: "Busitema",
    type: "public" as const,
    status: "chartered" as const,
    description: "Engineering and agriculture focused institution with emphasis on practical skills and innovation.",
    tuitionMin: "1600000",
    tuitionMax: "4200000",
    websiteUrl: "https://www.busitema.ac.ug",
    logoUrl: "https://busitema.ac.ug/wp-content/uploads/2021/03/busitema-logo.png",
    established: 2007,
    specialties: ["Engineering", "Agriculture", "Applied Sciences", "Health Sciences"]
  },
  {
    name: "Mbarara University of Science and Technology",
    location: "Mbarara",
    type: "public" as const,
    status: "chartered" as const,
    description: "Leading institution for science, technology, and health sciences with strong research programs and modern facilities.",
    tuitionMin: "2000000",
    tuitionMax: "5000000",
    websiteUrl: "https://www.must.ac.ug",
    logoUrl: "https://must.ac.ug/wp-content/uploads/2020/01/must-logo.png",
    established: 1989,
    specialties: ["Medicine", "Science & Technology", "Health Sciences", "Computing", "Development Studies"]
  },
  {
    name: "Muni University",
    location: "Arua",
    type: "public" as const,
    status: "chartered" as const,
    description: "Serving the West Nile region with focus on regional development and community engagement.",
    tuitionMin: "1700000",
    tuitionMax: "4300000",
    websiteUrl: "https://www.muni.ac.ug",
    logoUrl: "https://muni.ac.ug/images/muni-logo.png",
    established: 2013,
    specialties: ["Medicine", "Applied Sciences", "Education", "Agriculture"]
  },
  {
    name: "Kabale University",
    location: "Kabale",
    type: "public" as const,
    status: "chartered" as const,
    description: "Southwestern regional university with emphasis on agriculture and development studies.",
    tuitionMin: "1500000",
    tuitionMax: "4000000",
    websiteUrl: "https://www.kab.ac.ug",
    logoUrl: "https://kab.ac.ug/wp-content/uploads/2020/01/kabale-logo.png",
    established: 2015,
    specialties: ["Agriculture", "Education", "Development Studies", "Business"]
  },
  {
    name: "Soroti University",
    location: "Soroti",
    type: "public" as const,
    status: "chartered" as const,
    description: "Eastern Uganda university focusing on agriculture, education, and regional development.",
    tuitionMin: "1600000",
    tuitionMax: "4100000",
    websiteUrl: "https://www.soru.ac.ug",
    logoUrl: "https://soru.ac.ug/images/soroti-logo.png",
    established: 2015,
    specialties: ["Agriculture", "Education", "Applied Sciences", "Business"]
  },
  {
    name: "Lira University",
    location: "Lira",
    type: "public" as const,
    status: "chartered" as const,
    description: "Northern Uganda university focusing on agriculture, education, and regional development.",
    tuitionMin: "1600000",
    tuitionMax: "4100000",
    websiteUrl: "https://www.lirauni.ac.ug",
    logoUrl: "https://lirauni.ac.ug/images/lira-logo.png",
    established: 2015,
    specialties: ["Agriculture", "Education", "Applied Sciences"]
  },
  {
    name: "Mountains of the Moon University",
    location: "Fort Portal",
    type: "public" as const,
    status: "chartered" as const,
    description: "Regional university serving western Uganda with focus on community development.",
    tuitionMin: "2100000",
    tuitionMax: "4800000",
    websiteUrl: "https://www.mmu.ac.ug",
    logoUrl: "https://mmu.ac.ug/images/mmu-logo.png",
    established: 2005,
    specialties: ["Health Sciences", "Business", "Education", "Development Studies"]
  },
  {
    name: "Uganda Christian University",
    location: "Mukono",
    type: "private" as const,
    status: "chartered" as const,
    description: "First private chartered university (2004) offering quality education with Christian values and holistic development.",
    tuitionMin: "3000000",
    tuitionMax: "6000000",
    websiteUrl: "https://www.ucu.ac.ug",
    logoUrl: "https://ucu.ac.ug/images/ucu-logo.png",
    established: 1997,
    specialties: ["Theology", "Business", "Law", "Journalism", "Education", "Social Sciences"]
  },
  {
    name: "Uganda Martyrs University",
    location: "Nkozi",
    type: "private" as const,
    status: "chartered" as const,
    description: "Catholic university known for excellence in liberal arts, business, and social sciences education.",
    tuitionMin: "2800000",
    tuitionMax: "5800000",
    websiteUrl: "https://www.umu.ac.ug",
    logoUrl: "https://umu.ac.ug/images/umu-logo.png",
    established: 1993,
    specialties: ["Business", "Social Sciences", "Education", "Ethics & Development Studies"]
  },
  {
    name: "Islamic University in Uganda",
    location: "Mbale",
    type: "private" as const,
    status: "chartered" as const,
    description: "Islamic institution offering diverse programs with emphasis on Islamic values, ethics, and comprehensive education.",
    tuitionMin: "2000000",
    tuitionMax: "5500000",
    websiteUrl: "https://www.iuiu.ac.ug",
    logoUrl: "https://iuiu.ac.ug/images/iuiu-logo.png",
    established: 1988,
    specialties: ["Islamic Studies", "Education", "Management", "Science & Technology"]
  },
  {
    name: "Ndejje University",
    location: "Luwero",
    type: "private" as const,
    status: "chartered" as const,
    description: "One of Uganda's oldest private universities established in 1992, offering diverse academic programs.",
    tuitionMin: "2200000",
    tuitionMax: "5200000",
    websiteUrl: "https://www.ndejjeuniversity.ac.ug",
    logoUrl: "https://ndejjeuniversity.ac.ug/images/ndejje-logo.png",
    established: 1992,
    specialties: ["Business", "Education", "Social Sciences", "Information Technology"]
  },
  {
    name: "Nkumba University",
    location: "Entebbe",
    type: "private" as const,
    status: "chartered" as const,
    description: "Business-focused private university located near Lake Victoria with modern facilities.",
    tuitionMin: "2400000",
    tuitionMax: "5600000",
    websiteUrl: "https://www.nkumbauniversity.ac.ug",
    logoUrl: "https://nkumbauniversity.ac.ug/images/nkumba-logo.png",
    established: 1994,
    specialties: ["Business", "Computing", "Social Sciences", "Mass Communication"]
  },
  {
    name: "Kampala International University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Comprehensive private university with diverse programs and international partnerships for global education opportunities.",
    tuitionMin: "2500000",
    tuitionMax: "7000000",
    websiteUrl: "https://www.kiu.ac.ug",
    logoUrl: "https://kiu.ac.ug/images/kiu-logo.png",
    established: 2001,
    specialties: ["Medicine", "Engineering", "Business", "Law", "Pharmacy", "Nursing"]
  },
  {
    name: "Kampala University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Urban private university offering business and social sciences programs in the heart of Kampala.",
    tuitionMin: "2300000",
    tuitionMax: "5500000",
    websiteUrl: "https://www.ku.ac.ug",
    logoUrl: "https://ku.ac.ug/images/ku-logo.png",
    established: 2005,
    specialties: ["Business", "Social Sciences", "Education", "Information Technology"]
  },
  {
    name: "Bugema University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Seventh-day Adventist university offering holistic education with emphasis on Christian values.",
    tuitionMin: "2300000",
    tuitionMax: "5400000",
    websiteUrl: "https://www.bugema.ac.ug",
    logoUrl: "https://bugema.ac.ug/images/bugema-logo.png",
    established: 1994,
    specialties: ["Theology", "Business", "Education", "Health Sciences"]
  },
  {
    name: "Busoga University",
    location: "Iganga",
    type: "private" as const,
    status: "chartered" as const,
    description: "Serving the Busoga region with diverse academic programs and community development focus.",
    tuitionMin: "2100000",
    tuitionMax: "5000000",
    websiteUrl: "https://www.busogauniversity.ac.ug",
    logoUrl: "https://busogauniversity.ac.ug/images/busoga-logo.png",
    established: 1999,
    specialties: ["Business", "Education", "Agriculture", "Health Sciences"]
  },
  {
    name: "Bishop Stuart University",
    location: "Mbarara",
    type: "private" as const,
    status: "chartered" as const,
    description: "Anglican university in southwestern Uganda focusing on holistic education.",
    tuitionMin: "2200000",
    tuitionMax: "5000000",
    websiteUrl: "https://www.bsu.ac.ug",
    logoUrl: "https://bsu.ac.ug/images/bsu-logo.png",
    established: 2003,
    specialties: ["Theology", "Education", "Development Studies", "Business"]
  },
  {
    name: "Clarke International University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Health sciences focused university providing quality medical and nursing education.",
    tuitionMin: "3500000",
    tuitionMax: "8000000",
    websiteUrl: "https://www.ciu.ac.ug",
    logoUrl: "https://ciu.ac.ug/images/ciu-logo.png",
    established: 2008,
    specialties: ["Medicine", "Nursing", "Public Health", "Pharmacy"]
  },
  {
    name: "Victoria University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Recently chartered university offering contemporary programs in business and technology.",
    tuitionMin: "2800000",
    tuitionMax: "6500000",
    websiteUrl: "https://www.vu.ac.ug",
    logoUrl: "https://vu.ac.ug/images/vu-logo.png",
    established: 2011,
    specialties: ["Business", "Information Technology", "Social Sciences"]
  },
  {
    name: "International University of East Africa",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Technology and business focused university with modern programs and facilities.",
    tuitionMin: "2600000",
    tuitionMax: "6200000",
    websiteUrl: "https://www.iuea.ac.ug",
    logoUrl: "https://iuea.ac.ug/images/iuea-logo.png",
    established: 2010,
    specialties: ["Information Technology", "Business", "Engineering", "Health Sciences"]
  },
  {
    name: "Cavendish University Uganda",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "International university offering globally recognized programs with modern facilities.",
    tuitionMin: "3200000",
    tuitionMax: "7200000",
    websiteUrl: "https://www.cavendish.ac.ug",
    logoUrl: "https://cavendish.ac.ug/images/cavendish-logo.png",
    established: 2008,
    specialties: ["Business", "Law", "Psychology", "Information Technology"]
  },
  {
    name: "St. Lawrence University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Private university offering business and social sciences programs with strong industry connections.",
    tuitionMin: "2500000",
    tuitionMax: "5800000",
    websiteUrl: "https://www.slau.ac.ug",
    logoUrl: "https://slau.ac.ug/images/slau-logo.png",
    established: 2007,
    specialties: ["Business", "Education", "Social Sciences", "Information Technology"]
  },
  {
    name: "African Bible University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Christian university focused on biblical studies and leadership development.",
    tuitionMin: "2000000",
    tuitionMax: "4500000",
    websiteUrl: "https://www.abu.ac.ug",
    logoUrl: "https://abu.ac.ug/images/abu-logo.png",
    established: 2005,
    specialties: ["Theology", "Biblical Studies", "Leadership", "Education"]
  },
  {
    name: "Uganda Pentecostal University",
    location: "Fort Portal",
    type: "private" as const,
    status: "chartered" as const,
    description: "Pentecostal university offering education rooted in Christian values and community service.",
    tuitionMin: "2200000",
    tuitionMax: "5100000",
    websiteUrl: "https://www.upu.ac.ug",
    logoUrl: "https://upu.ac.ug/images/upu-logo.png",
    established: 2005,
    specialties: ["Theology", "Education", "Business", "Social Work"]
  },
  {
    name: "Team University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Modern private university with innovative programs and entrepreneurship focus.",
    tuitionMin: "2400000",
    tuitionMax: "5600000",
    websiteUrl: "https://www.teamuniversity.ac.ug",
    logoUrl: "https://teamuniversity.ac.ug/images/team-logo.png",
    established: 2009,
    specialties: ["Business", "Information Technology", "Media Studies", "Social Sciences"]
  },
  {
    name: "Kayiwa International University",
    location: "Kampala",
    type: "private" as const,
    status: "chartered" as const,
    description: "Private university offering diverse programs with international standards.",
    tuitionMin: "2600000",
    tuitionMax: "6000000",
    websiteUrl: "https://www.kayiwa.ac.ug",
    logoUrl: "https://kayiwa.ac.ug/images/kayiwa-logo.png",
    established: 2010,
    specialties: ["Business", "Education", "Health Sciences", "Information Technology"]
  },
  {
    name: "Kisubi University",
    location: "Entebbe",
    type: "private" as const,
    status: "chartered" as const,
    description: "Catholic university offering quality education with strong community engagement.",
    tuitionMin: "2500000",
    tuitionMax: "5700000",
    websiteUrl: "https://www.kisubi.ac.ug",
    logoUrl: "https://kisubi.ac.ug/images/kisubi-logo.png",
    established: 2008,
    specialties: ["Business", "Education", "Social Sciences", "Development Studies"]
  }
];

export const ugandaScholarshipsData = [
  {
    title: "Uganda Government Scholarship Scheme",
    description: "Full tuition coverage for exceptional students pursuing undergraduate degrees in public universities across Uganda. Merit-based selection with focus on academic excellence.",
    provider: "Government of Uganda",
    amount: "5000000",
    currency: "UGX",
    eligibility: "Ugandan citizens with excellent academic performance, financial need demonstration, and commitment to national development.",
    level: "undergraduate" as const,
    type: "government" as const,
    deadline: new Date("2025-03-30"),
    applicationUrl: "https://www.education.go.ug/scholarships",
    isActive: true
  },
  {
    title: "Mastercard Foundation Scholars Program",
    description: "Comprehensive scholarship covering tuition, accommodation, and mentorship for undergraduate studies at partner universities.",
    provider: "Mastercard Foundation",
    amount: "15000000",
    currency: "UGX",
    eligibility: "Academically talented students from disadvantaged backgrounds with leadership potential.",
    level: "undergraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-02-15"),
    applicationUrl: "https://mastercardfdn.org/scholars/",
    isActive: true
  },
  {
    title: "Commonwealth Scholarship",
    description: "Fully funded masters and PhD opportunities in UK universities for students from Commonwealth countries.",
    provider: "Commonwealth Scholarship Commission",
    amount: "25000000",
    currency: "UGX",
    eligibility: "First-class or upper second-class honors degree, proven academic merit.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2024-12-20"),
    applicationUrl: "https://cscuk.fcdo.gov.uk/",
    isActive: true
  },
  {
    title: "DAAD Scholarships",
    description: "German Academic Exchange Service scholarships for postgraduate studies in Germany.",
    provider: "DAAD Germany",
    amount: "18000000",
    currency: "UGX",
    eligibility: "Bachelor's degree in relevant field, two years work experience.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-01-31"),
    applicationUrl: "https://www.daad.org/en/",
    isActive: true
  },
  {
    title: "Uganda Women's Scholarship Fund",
    description: "Supporting female students in STEM fields and traditionally male-dominated disciplines.",
    provider: "Uganda Women's Education Foundation",
    amount: "3000000",
    currency: "UGX",
    eligibility: "Female students enrolled in STEM programs, demonstration of financial need.",
    level: "both" as const,
    type: "private" as const,
    deadline: new Date("2025-04-15"),
    isActive: true
  },
  {
    title: "USAID Higher Education Scholarship",
    description: "Merit-based scholarships for students pursuing degrees in agriculture, health, education, and business.",
    provider: "USAID Uganda",
    amount: "8000000",
    currency: "UGX",
    eligibility: "Strong academic performance, leadership potential.",
    level: "both" as const,
    type: "international" as const,
    deadline: new Date("2025-03-15"),
    applicationUrl: "https://www.usaid.gov/uganda/education",
    isActive: true
  },
  {
    title: "Chevening Scholarships",
    description: "UK government's global scholarship for fully-funded one-year master's degrees for future leaders.",
    provider: "UK Foreign, Commonwealth & Development Office",
    amount: "30000000",
    currency: "UGX",
    eligibility: "Bachelor's degree, two years work experience, leadership potential.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2024-11-05"),
    applicationUrl: "https://www.chevening.org/",
    isActive: true
  },
  {
    title: "Islamic Development Bank Scholarship",
    description: "Scholarships for undergraduate and postgraduate studies with preference for science and technology.",
    provider: "Islamic Development Bank",
    amount: "12000000",
    currency: "UGX",
    eligibility: "Muslim students with strong academic record, financial need.",
    level: "both" as const,
    type: "international" as const,
    deadline: new Date("2025-02-28"),
    applicationUrl: "https://www.isdb.org/scholarships",
    isActive: true
  },
  {
    title: "Uganda Petroleum Institute Scholarship",
    description: "Scholarships for students pursuing petroleum and energy-related studies.",
    provider: "Uganda Petroleum Institute",
    amount: "4500000",
    currency: "UGX",
    eligibility: "Students in petroleum engineering, geology, and related fields.",
    level: "both" as const,
    type: "government" as const,
    deadline: new Date("2025-03-20"),
    isActive: true
  },
  {
    title: "African Development Bank Scholarship",
    description: "Supporting African students in higher education with focus on development fields.",
    provider: "African Development Bank",
    amount: "10000000",
    currency: "UGX",
    eligibility: "African nationals with strong academic credentials.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-01-15"),
    applicationUrl: "https://www.afdb.org/en/about/careers/scholarship-program",
    isActive: true
  },
  {
    title: "Fulbright Foreign Student Program",
    description: "Full scholarship for Ugandan students to pursue graduate studies in the United States.",
    provider: "U.S. Department of State",
    amount: "35000000",
    currency: "UGX",
    eligibility: "Bachelor's degree, English proficiency, leadership experience.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-04-30"),
    applicationUrl: "https://ug.usembassy.gov/education-culture/fulbright-program/",
    isActive: true
  },
  {
    title: "MTN Uganda Foundation Scholarship",
    description: "Supporting bright students from underserved communities in STEM education.",
    provider: "MTN Uganda Foundation",
    amount: "4000000",
    currency: "UGX",
    eligibility: "Students from underserved communities with strong STEM aptitude.",
    level: "undergraduate" as const,
    type: "private" as const,
    deadline: new Date("2025-05-31"),
    isActive: true
  },
  {
    title: "Stanbic Bank Uganda Scholarship",
    description: "Supporting students in business and finance programs with full tuition coverage.",
    provider: "Stanbic Bank Uganda",
    amount: "5000000",
    currency: "UGX",
    eligibility: "Students pursuing business, economics, or finance degrees.",
    level: "undergraduate" as const,
    type: "private" as const,
    deadline: new Date("2025-03-01"),
    isActive: true
  },
  {
    title: "Japan MEXT Scholarship",
    description: "Full scholarship for undergraduate and postgraduate studies in Japan.",
    provider: "Japanese Government",
    amount: "20000000",
    currency: "UGX",
    eligibility: "Under 35 years old, excellent academic record, good health.",
    level: "both" as const,
    type: "international" as const,
    deadline: new Date("2025-04-10"),
    applicationUrl: "https://www.studyinjapan.go.jp/en/smap_stopj-applications_research.html",
    isActive: true
  },
  {
    title: "Mandela Rhodes Scholarship",
    description: "Leadership scholarship for young Africans to study in South Africa.",
    provider: "Mandela Rhodes Foundation",
    amount: "22000000",
    currency: "UGX",
    eligibility: "African under 30, completed undergraduate degree, leadership potential.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-02-20"),
    applicationUrl: "https://www.mandelarhodes.org/",
    isActive: true
  },
  {
    title: "Australia Awards Scholarship",
    description: "Fully funded scholarships for students from developing countries to study in Australia.",
    provider: "Australian Government",
    amount: "28000000",
    currency: "UGX",
    eligibility: "Work experience in development sector, commitment to return.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-04-25"),
    applicationUrl: "https://www.dfat.gov.au/people-to-people/australia-awards",
    isActive: true
  },
  {
    title: "Rotary Peace Fellowship",
    description: "Fellowship for students pursuing studies in peace and conflict resolution.",
    provider: "Rotary International",
    amount: "25000000",
    currency: "UGX",
    eligibility: "Work experience in peace-related fields, commitment to service.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-05-15"),
    applicationUrl: "https://www.rotary.org/en/our-programs/peace-fellowships",
    isActive: true
  },
  {
    title: "UNICEF Youth Scholarship",
    description: "Supporting young people pursuing studies in child development and social work.",
    provider: "UNICEF Uganda",
    amount: "6000000",
    currency: "UGX",
    eligibility: "Students in social work, education, or health programs.",
    level: "undergraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-06-01"),
    isActive: true
  },
  {
    title: "Centenary Bank Scholarship",
    description: "Merit-based scholarship for students from rural communities.",
    provider: "Centenary Bank Uganda",
    amount: "3500000",
    currency: "UGX",
    eligibility: "Students from rural areas with strong academic performance.",
    level: "undergraduate" as const,
    type: "private" as const,
    deadline: new Date("2025-03-15"),
    isActive: true
  },
  {
    title: "World Bank Graduate Scholarship",
    description: "Supporting students from developing countries in graduate studies related to development.",
    provider: "World Bank",
    amount: "32000000",
    currency: "UGX",
    eligibility: "Work experience in development, commitment to return to home country.",
    level: "postgraduate" as const,
    type: "international" as const,
    deadline: new Date("2025-02-01"),
    applicationUrl: "https://www.worldbank.org/en/programs/scholarships",
    isActive: true
  }
];

export const servicesData = [
  {
    name: "Apply to Universities",
    description: "Complete application assistance from document preparation to submission for your dream university.",
    price: "150000",
    currency: "UGX",
    isActive: true
  },
  {
    name: "Win Scholarships",
    description: "Personalized scholarship search and application strategy to maximize your funding opportunities.",
    price: "200000",
    currency: "UGX",
    isActive: true
  },
  {
    name: "Craft Resume",
    description: "Professional resume and CV writing services tailored for academic and scholarship applications.",
    price: "75000",
    currency: "UGX",
    isActive: true
  },
  {
    name: "Career Guidance",
    description: "One-on-one consultation with career experts for career planning and professional development.",
    price: "100000",
    currency: "UGX",
    isActive: true
  },
  {
    name: "SOP Writing",
    description: "Expert Statement of Purpose writing services to help you stand out in competitive admissions.",
    price: "120000",
    currency: "UGX",
    isActive: true
  },
  {
    name: "Application Follow-up",
    description: "Post-submission support including status tracking and communication with admissions offices.",
    price: "80000",
    currency: "UGX",
    isActive: true
  }
];
